dist: xenial

sudo: false

matrix:
  include:

    - name: "OpenJDK 8"
      language: java
      jdk: openjdk8
      os: linux
      script: ./gradlew --scan

    - name: "OpenJDK 11"
      language: java
      jdk: openjdk11
      os: linux
      script: ./gradlew --scan

    - name: "C#"
      language: csharp
      jdk: openjdk8
      dotnet: 2.2
      os: linux
      mono: latest
      global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
        - DOTNET_CLI_TELEMETRY_OPTOUT=1
      script:
        - ./csharp/build.sh
        - ./csharp/runtests.sh
        - ./csharp/pack.sh

    - name: "GCC 5" 
      env: COMPILER=g++-5
      language: cpp
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - g++-5
            - libsparsehash-dev
          sources:
            - ubuntu-toolchain-r-test
      script: ./cppbuild/cppbuild

    - name: "GCC 6" 
      env: COMPILER=g++-6
      language: cpp
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - g++-6
            - libsparsehash-dev
          sources:
            - ubuntu-toolchain-r-test
      script: ./cppbuild/cppbuild

    - name: "GCC 7" 
      env: COMPILER=g++-7
      language: cpp
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - g++-7
            - libsparsehash-dev
          sources:
            - ubuntu-toolchain-r-test
      script: ./cppbuild/cppbuild

    - name: "GCC 8" 
      env: COMPILER=g++-8
      language: cpp
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - g++-8
            - libsparsehash-dev
          sources:
            - ubuntu-toolchain-r-test
      script: ./cppbuild/cppbuild

    - name: "GCC 9" 
      env: COMPILER=g++-9
      language: cpp
      compiler: gcc
      os: linux
      addons:
        apt:
          packages:
            - g++-9
            - libsparsehash-dev
          sources:
            - ubuntu-toolchain-r-test
      script: ./cppbuild/cppbuild

    - name: "Clang 5" 
      env: COMPILER=clang++-5.0
      language: cpp
      compiler: clang
      os: linux
      addons:
        apt:
          packages:
            - clang-5.0
            - libsparsehash-dev
          sources:
            - llvm-toolchain-xenial-5.0
      script: ./cppbuild/cppbuild

    - name: "Clang 6" 
      env: COMPILER=clang++-6.0
      language: cpp
      compiler: clang
      os: linux
      addons:
        apt:
          packages:
            - clang-6.0
            - libsparsehash-dev
          sources:
            - llvm-toolchain-xenial-6.0
      script: ./cppbuild/cppbuild

    - name: "Clang 7" 
      env: COMPILER=clang++-7
      language: cpp
      compiler: clang
      os: linux
      addons:
        apt:
          packages:
            - clang-7
            - libsparsehash-dev
          sources:
            - llvm-toolchain-xenial-7
      script: ./cppbuild/cppbuild

    - name: "Clang 8" 
      env: COMPILER=clang++-8
      language: cpp
      compiler: clang
      os: linux
      addons:
        apt:
          packages:
            - clang-8
            - libsparsehash-dev
          sources:
            - llvm-toolchain-xenial-8
      script: ./cppbuild/cppbuild

    - name: "macOS"
      env: COMPILER=clang++
      language: c++
      compiler: clang
      os: osx
      script: ./cppbuild/cppbuild


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
